version: '3'
services:
  # rabbit-mq:
  #   image: rabbitmq:3-management
  #   container_name: sps-rabbit-mq
  #   networks:
  #     - sps-network
  #   restart: unless-stopped
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"

  postgres:
    image: postgres:sps-laster
    container_name: sps-postgres
    hostname: '${POSTGRES_HOST}'
    build:
      context: ./postgresql/
      args:
        PGID: 1000
    restart: unless-stopped
    networks:
      - sps-network
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DATABASE}"
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    env_file:
      - .env

  api:
    image: api-teste-sps:laster
    container_name: api-teste-sps
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules

    environment:
      - POSTGRES_HOST=postgres
    networks:
      - sps-network
    command: npm run dev
    depends_on:
      - postgres

volumes:
  postgresql_data:
    driver: local
networks:
  sps-network:
